language: rust
dist: trusty
rust:
  - stable
  - beta
  - nightly-2016-04-29
  - nightly

env:
  - CXX=g++-4.8

node_js:
  - 6.0
  - 5.0
  - 5.11
  - 4.2

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

script:
- |
  (cd tests/ && npm test)
  if [[ "$TRAVIS_RUST_VERSION" == nightly* ]]; then
    (cd compile_tests/ && travis-cargo test)
  fi

