[package]
name = "neon"
version = "0.3.1"
authors = ["Dave Herman <david.herman@gmail.com>"]
description = "A safe abstraction layer for Node.js."
readme = "README.md"
documentation = "https://api.neon-bindings.com/neon/index.html"
homepage = "https://www.neon-bindings.com"
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"
exclude = ["neon.jpg"]
build = "build.rs"

[build-dependencies]
neon-build = { version = "=0.3.1", path = "crates/neon-build" }

[dev-dependencies]
lazy_static = "1.4.0"

[dependencies]
cfg-if = "0.1.9"
cslice = "0.2"
semver = "0.9.0"
neon-runtime = { version = "=0.3.1", path = "crates/neon-runtime" }

[features]
default = ["legacy-runtime"]

# Feature flag to enable the legacy V8/NAN runtime. For now, this feature is
# enabled by default. Disabling the feature uses the experimental N-API runtime
# instead. If the N-API works out, once it's complete we'll be able to turn this
# flag off by default and eventually remove the legacy runtime entirely.
legacy-runtime = ["neon-runtime/neon-sys", "neon-build/neon-sys"]

[workspace]
members = [
    "crates/neon-build",
    "crates/neon-runtime",
    "crates/neon-sys",
    "test/static",
    "test/electron/native",
    "test/dynamic/native",
]
