[package]
name = "neon"
version = "0.0.10"
authors = ["Dave Herman <dherman@mozilla.com>"]
description = "A safe abstraction layer for Node.js."
repository = "https://github.com/dherman/neon"
license = "MIT"
exclude = ["neon.jpg"]

[dependencies]
neon-sys = { version = "0.0.7", path = "crates/neon-sys" }
