[package]
name = "nanny"
version = "0.0.9"
authors = ["Dave Herman <dherman@mozilla.com>"]
description = "Safe native abstractions for Node."
repository = "https://github.com/dherman/nanny"
license = "MIT"
exclude = ["silhouette.png"]

[dependencies]
nanny-sys = { version = "0.0.6", path = "crates/nanny-sys" }
