[package]
name = "neon"
version = "0.1.4"
authors = ["Dave Herman <dherman@mozilla.com>"]
description = "A safe abstraction layer for Node.js."
repository = "https://github.com/rustbridge/neon"
license = "MIT"
exclude = ["neon.jpg"]

[dependencies]
neon-sys = { version = "=0.1.4", path = "crates/neon-sys" }
