[package]
name = "neon-runtime"
version = "0.3.1"
authors = ["Dave Herman <david.herman@gmail.com>"]
description = "Bindings to the Node.js native addon API, used by the Neon implementation."
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"

# Sharing the name of the library produced by neon-runtime allows the
# `build.rs` script for Neon projects to find the path to `node.lib`
# in Windows.
#
# See also: http://doc.crates.io/build-script.html#the-links-manifest-key
links = "neon-sys"
build = "build.rs"

[dependencies]
cfg-if = "0.1.9"
# When it's time to publish this, we'll add an explicit version, e.g.:
# neon-sys = { version = "=0.3.1", path = "../neon-sys", optional = true }
neon-sys = { path = "../neon-sys", optional = true }
